/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

fun calculateScore(input: String): Int {
    var score = 0
    if (input[0] != '-') score += input[0].digitToInt()
    if (input[1] != '-') score += input[1].digitToInt()
    if (input[9] != '-') score += 4
    if (input[12] != '-') score += 7
    if (input[13] != '-') score += input[13].digitToInt()

    return score
}
