/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class CalculateScoreTest {
    @Test
    fun `returns 0 for no pins knocked down`() {
        assertThatcalculateScore("--|--|--|--|--|--|--|--|--|--||")).isEqualTo(0)
    }
}
